---
# tasks file for ansible-role-autofs


# ----- Setup -----
- name: "Setup | apt | ensure autofs's package(s) present"
  apt: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'apt'


- name: "Setup | yum | ensure autofs's package(s) present"
  yum: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'yum'


- name: "Setup | zyp | ensure autofs's package(s) present"
  zypper: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'zypper'


# ----- Config -----
- name: "Config| all | ensure indirect map paths(s) exist"
  file: path="{{ autofs_indirect_maps[path] }}" state=directory
  with_items: autofs_indirect_maps

