---
# tasks file for ansible-role-autofs


# ----- Setup -----
- name: "Setup | apt | ensure autofs's package(s) present"
  apt: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'apt'


- name: "Setup | yum | ensure autofs's package(s) present"
  yum: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'yum'


- name: "Setup | zyp | ensure autofs's package(s) present"
  zypper: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'zypper'


# ----- Config -----
- name: "Config| all | ensure indirect map paths(s) exist"
  file: path="{{ autofs_indirect_maps[path] }}" state=directory
  with_items: autofs_indirect_maps


- name: "Config| all | create indirect map file(s) from template"
  template: src="indirect_map.j2" dest="/etc/{{ autofs_indirect_maps[name] }}" mode=600
  with_items: autofs_indirect_maps


- name: "Config| all | add indirect map file(s) to autofs master file"
  lineinfile: dest="{{ autofs_path_master[ ansible_system ] }}" line="{{ autofs_indirect_maps[path] }}     {{ autofs_indirect_maps[name] }}"
  with_items: autofs_indirect_maps

