---
# tasks file for ansible-role-autofs


# ----- Setup -----
- name: "Setup | apt | ensure autofs's package(s) present"
  apt: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'apt'


- name: "Setup | yum | ensure autofs's package(s) present"
  yum: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'yum'


- name: "Setup | zyp | ensure autofs's package(s) present"
  zypper: name="{{ item }}"
  with_items: autofs_pkgs[ ansible_system ]
  when: ansible_pkg_mgr == 'zypper'

